spring:
  application:
    name: orielle-account-service
  main:
    web-application-type: reactive
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: orielle-account-service
